/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import static guis.ManageContacts.contacts;
import java.io.File;
/**
 *
 * @author Hanane Nour
 */
public class ContactJFrame extends javax.swing.JFrame {
    
     public static final String pathToHome = System.getProperty("user.home")
             + File.separator+ "whatsapp"+File.separator+"phonebook.ser";

    /**
     * Creates new form ContactJFrame
     */
    public ContactJFrame() {
        initComponents();
        registerListeners();
    }
    public void registerListeners (){
        saveItem.addActionListener(new ActionListener (){
             @Override
             public void actionPerformed (ActionEvent evt){
                 contacts.save(pathToHome);
                 JOptionPane.showMessageDialog (ContactJFrame.this,
                         "Contacts Saved To Phonebook!", "Saving...",
                         JOptionPane.INFORMATION_MESSAGE);
             }
        }
        );
        
        exitItem.addActionListener (new ActionListener (){
            @Override
            public void actionPerformed (ActionEvent evt)
                {
                    JOptionPane.showMessageDialog (ContactJFrame.this, 
                            "Exiting...", "Thank you for using Whatsapp!", 
                            JOptionPane.INFORMATION_MESSAGE);
                    System.exit(0);
                }
        }
        );
        
        aboutItem.addActionListener (new ActionListener ()
                {
                    @Override 
                    public void actionPerformed (ActionEvent evt){
                        JOptionPane.showMessageDialog (ContactJFrame.this, "Whatsapp"
                                + " is a free platform that allows users to send text messages and voice messages"
                                + ", make voice and video calls, and share images,"
                                + " documents, user locations, and other media.", "About...", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        AddPane = new javax.swing.JTabbedPane();
        manageContacts2 = new guis.ManageContacts();
        searchContact1 = new guis.SearchContact();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutItem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddPane.setName("Manage Contacts"); // NOI18N
        AddPane.addTab("Manage Contacts", manageContacts2);
        AddPane.addTab("Search Contacts", searchContact1);

        fileMenu.setText("File");

        saveItem.setText("Save");
        fileMenu.add(saveItem);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitItem);

        jMenuBar1.add(fileMenu);
        fileMenu.getAccessibleContext().setAccessibleName("Save");

        helpMenu.setText("Help");

        aboutItem.setText("About");
        helpMenu.add(aboutItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddPane, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(AddPane, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AddPane.getAccessibleContext().setAccessibleName("Manage Contacts");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AddPane;
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private guis.ManageContacts manageContacts2;
    private javax.swing.JMenuItem saveItem;
    private guis.SearchContact searchContact1;
    // End of variables declaration//GEN-END:variables
}
